import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
test.beforeEach(async ({ page }) => {
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.goto("/#brojac");
  await expect(page.getByRole("heading", { level: 1 })).toContainText("TI BACAJ");
});
test("phone: name customization, bull order, score, undo, handover, refresh, resume and navigation", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.getByLabel("Ime igrača 1", { exact: true }).fill("Ana");
  await page.getByLabel("Ime igrača 2", { exact: true }).fill("Tin");
  await page.getByLabel("Oznaka igrača 2", { exact: true }).fill("TG");
  await page.getByRole("button", { name: "Dogovori redoslijed" }).click();
  await page.getByRole("button", { name: "Pomakni Tin gore" }).click();
  await page.getByRole("button", { name: "Počni igru" }).click();
  await expect(page.locator(".current-player h2")).toHaveText("Tin");
  await page.getByRole("button", { name: "Triple ×3" }).click();
  await page.getByRole("button", { name: "T20", exact: true }).click();
  await expect(page.locator(".current-total strong")).toHaveText("441");
  await page.getByRole("button", { name: "Poništi zadnji unos" }).click();
  await expect(page.locator(".current-total strong")).toHaveText("501");
  for(let i=0; i<3; i++) await page.getByRole("button", { name: "20", exact: true }).click();
  await expect(page.getByRole("button", { name: "20", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Sljedeći: Ana" }).click();
  await expect(page.locator(".current-player h2")).toHaveText("Ana");
  await page.reload(); await page.getByRole("button", { name: "Nastavi igru" }).click();
  await expect(page.locator(".current-player h2")).toHaveText("Ana");
  await expect(page.locator(".score-list")).toContainText("441");
  await page.getByRole("link", { name: "Natrag u klub" }).click();
  await expect(page.locator(".hero")).toBeVisible();
  await page.goto("/#brojac");
  await page.getByRole("button", { name: "Nastavi igru" }).click();
  await expect(page.locator(".current-player h2")).toHaveText("Ana");
  expect(errors).toEqual([]);
});
test("up to ten players, randomized order, Cricket scoring table and no overflow", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  for (let i=0; i<8; i++) await page.getByRole("button", { name: /Dodaj igrača/ }).click();
  await expect(page.getByRole("button", { name: /Dodaj igrača/ })).toBeDisabled();
  await page.getByRole("button", { name: "Cricket Zatvori. Osvajaj.", exact: true }).click();
  await page.getByLabel("Tko prvi baca?").selectOption("random");
  await page.getByRole("button", { name: "Dogovori redoslijed" }).click();
  await expect(page.locator(".order-list li")).toHaveCount(10);
  const names = await page.locator(".order-list strong").allTextContents();
  expect(new Set(names).size).toBe(10);
  await page.getByRole("button", { name: "Počni igru" }).click();
  await page.getByRole("button", { name: "Triple ×3" }).click();
  await page.getByRole("button", { name: "T20", exact: true }).click();
  await page.getByRole("button", { name: "20", exact: true }).click();
  await expect(page.locator(".current-total strong")).toHaveText("20");
  await expect(page.locator(".cricket-table td.closed")).toHaveCount(1);
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test("setup and match accessibility; confirmation cancellation preserves the game", async ({ page }) => {
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.getByRole("button", { name: "Dogovori redoslijed" }).click();
  await page.getByRole("button", { name: "Počni igru" }).click();
  await page.getByRole("button", { name: "20", exact: true }).click();
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await page.getByRole("button", { name: "Nova igra", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).not.toBeVisible();
  await expect(page.locator(".current-total strong")).toHaveText("481");
});
test("Shanghai instant win, undo winning dart and confirmed reset", async ({ page }) => {
  await page.getByRole("button", { name: "Shanghai Tri prstena. Jedan broj.", exact: true }).click();
  await page.getByRole("button", { name: "Dogovori redoslijed" }).click();
  await page.getByRole("button", { name: "Počni igru" }).click();
  await page.getByRole("button", { name: "1", exact: true }).click();
  await page.getByRole("button", { name: "Double ×2" }).click();
  await page.getByRole("button", { name: "D1", exact: true }).click();
  await page.getByRole("button", { name: "Triple ×3" }).click();
  await page.getByRole("button", { name: "T1", exact: true }).click();
  await expect(page.locator(".winner-panel")).toContainText("Shanghai!");
  await page.getByRole("button", { name: "Poništi zadnji unos" }).click();
  await expect(page.locator(".winner-panel")).toHaveCount(0);
  await expect(page.locator(".current-total strong")).toHaveText("3");
  await page.getByRole("button", { name: "Nova igra", exact: true }).click();
  await page.getByRole("dialog").getByRole("button", { name: "Nova igra", exact: true }).click();
  await expect(page.getByRole("heading", { level: 1 })).toContainText("TI BACAJ");
  expect(await page.evaluate(() => localStorage.getItem("pk-normal-counter-v1"))).toBeNull();
});
