import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',e=>{if(e.type()==='error') errors.push(e.text().slice(0,250));});
await page.goto('http://localhost:4173/#karta');
await expect(page.locator('.city-map-frame')).toHaveAttribute('data-map-status','ready',{timeout:25000});
const canvas=await page.locator('.maplibregl-canvas').boundingBox();
expect(canvas.width).toBeGreaterThan(300);expect(canvas.height).toBeGreaterThan(300);
await page.waitForTimeout(2000);
await page.screenshot({path:'docs/qa/atlas-desktop.png',fullPage:true});
await page.locator('.atlas-stage').screenshot({path:'docs/qa/atlas-stage-desktop.png'});
await page.getByRole('button',{name:'Cijeli grad',exact:true}).click();
await page.waitForTimeout(1500);
await page.locator('.atlas-stage').screenshot({path:'docs/qa/atlas-overview-desktop.png'});
await page.getByRole('button',{name:'BBF · Savska cesta 150, Zagreb',exact:true}).click();
await expect(page.locator('.atlas-match-panel')).toContainText('BBF BULLY BOYS');
await page.getByRole('button',{name:'3D prikaz',exact:true}).click();
await expect(page.getByRole('button',{name:'2D prikaz',exact:true})).toBeVisible();
await page.getByLabel('Odaberi igralište',{exact:true}).selectOption('exterium');
await expect(page.locator('.atlas-venue')).toContainText('CB Exterium');
await page.getByRole('button',{name:'Sjever gore',exact:true}).click();
await page.getByRole('button',{name:'Kup',exact:true}).click();
await expect(page.locator('.atlas-pin:not([hidden])')).toHaveCount(1);
await expect(page.locator('.atlas-match-panel')).toContainText('Pivana');
expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
for(const [width,height] of [[390,844],[430,932]]){
 await page.setViewportSize({width,height});
 await page.reload();
 await expect(page.locator('.city-map-frame')).toHaveAttribute('data-map-status','ready',{timeout:25000});
 await page.waitForTimeout(1500);
 await page.screenshot({path:`docs/qa/atlas-mobile-${width}.png`,fullPage:true});
 await page.locator('.atlas-stage').screenshot({path:`docs/qa/atlas-stage-mobile-${width}.png`});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Cijeli grad',exact:true}).click();
 await page.waitForTimeout(3000);
 await page.locator('.atlas-map').screenshot({path:`docs/qa/atlas-overview-mobile-${width}.png`});
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
}
expect(errors).toEqual([]);
console.log('Real map: nonzero canvas, marker selection, 2D/3D, filters, desktop/mobile accessibility and overflow checks passed.');
await browser.close();
